packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: ^19.2.0
  react-dom: ^19.2.0

  next: ^16.0.10

  "@tanstack/react-query": ^5.62.12
  "@tanstack/react-table": ^8.21.0

  lucide-react: ^0.469.0

  typescript: ^5.7.2
  eslint: ^9.17.0
  "@eslint/js": ^9.17.0
  "@next/eslint-plugin-next": ^15.1.0
  eslint-plugin-react: ^7.37.2
  eslint-plugin-react-hooks: ^5.1.0
  typescript-eslint: ^8.18.1

  tailwindcss: ^3.4.17
  postcss: ^8.4.51

  "@types/node": ^22.10.2
  "@types/react": ^19.0.2
  "@types/react-dom": ^19.0.2

  prettier: ^3.4.2
  turbo: ^2.3.3

  "@radix-ui/react-dialog": ^1.1.5
  "@radix-ui/react-popover": ^1.1.5
  "@radix-ui/react-slot": ^1.1.1
  "@radix-ui/react-tooltip": ^1.1.5

  clsx: ^2.1.1
  tailwind-merge: ^2.6.0
  class-variance-authority: ^0.7.1
  next-themes: ^0.4.6
  posthog-js: ^1.209.0
  tailwindcss-animate: ^1.0.7
