sonar.projectKey=data-projects
sonar.projectName=Data Projects

sonar.sources=apps/imdb-best-season/src,apps/spotify-popularity/src,apps/youtube/src,packages/shared/src,packages/ui/src

sonar.host.url=http://localhost:9000

sonar.sourceEncoding=UTF-8
